// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeUnionExampleAvro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class TypeWithUnionAvro : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""TypeWithUnionAvro"",""namespace"":""TypeUnionExampleAvro"",""fields"":[{""name"":""TopLevelField"",""type"":""string""},{""name"":""UnionField"",""type"":[{""type"":""record"",""name"":""ObjA"",""namespace"":""TypeUnionExampleAvro"",""fields"":[{""name"":""FieldA"",""type"":""string""}]},{""type"":""record"",""name"":""ObjB"",""namespace"":""TypeUnionExampleAvro"",""fields"":[{""name"":""FieldB"",""type"":""string""}]}]}]}");
		private string _TopLevelField;
		private object _UnionField;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TypeWithUnionAvro._SCHEMA;
			}
		}
		public string TopLevelField
		{
			get
			{
				return this._TopLevelField;
			}
			set
			{
				this._TopLevelField = value;
			}
		}
		public object UnionField
		{
			get
			{
				return this._UnionField;
			}
			set
			{
				this._UnionField = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TopLevelField;
			case 1: return this.UnionField;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TopLevelField = (System.String)fieldValue; break;
			case 1: this.UnionField = (System.Object)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
